//Scenario 2: UpdateEmployeeBonus
//Employees Table
CREATE TABLE EMPLOYEES (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    DEPARTMENT VARCHAR2(50),
    SALARY NUMBER
);

INSERT INTO EMPLOYEES VALUES (101,'Ravi','IT',30000);
INSERT INTO EMPLOYEES VALUES (102,'Sita','IT',40000);
INSERT INTO EMPLOYEES VALUES (103,'Ram','HR',35000);

COMMIT;
SELECT * FROM EMPLOYEES;

CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(
    p_department VARCHAR2,
    p_bonus NUMBER
)
IS
BEGIN
    UPDATE EMPLOYEES
    SET SALARY = SALARY + (SALARY * p_bonus / 100)
    WHERE DEPARTMENT = p_department;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Bonus Updated Successfully');
END;
/

EXEC UpdateEmployeeBonus('IT',10);
DESC EMPLOYEES;
ALTER TABLE EMPLOYEES
ADD DEPARTMENT VARCHAR2(50);
DESC EMPLOYEES;
UPDATE EMPLOYEES
SET DEPARTMENT='IT'
WHERE EMP_ID=101;

UPDATE EMPLOYEES
SET DEPARTMENT='IT'
WHERE EMP_ID=102;

UPDATE EMPLOYEES
SET DEPARTMENT='HR'
WHERE EMP_ID=103;

COMMIT;

EXEC UpdateEmployeeBonus('IT',10);

//verification
SELECT * FROM EMPLOYEES;