CREATE TABLE LOANS (
   LOAN_ID NUMBER PRIMARY KEY,
   CUSTOMER_ID NUMBER,
   DUE_DATE DATE,
   AMOUNT NUMBER
);
SELECT * FROM LOANS;
SET SERVEROUTPUT ON;

BEGIN
   FOR l IN (
      SELECT LOAN_ID, CUSTOMER_ID, DUE_DATE
      FROM LOANS
      WHERE DUE_DATE BETWEEN SYSDATE AND SYSDATE + 30
   )
   LOOP
      DBMS_OUTPUT.PUT_LINE(
         'Reminder: Customer ID '
         || l.CUSTOMER_ID
         || ' Loan ID '
         || l.LOAN_ID
      );
   END LOOP;
END;
/
SELECT * FROM LOANS;